### ISSUE TITLE
[Track 3 | Technical Blog] Implementing Governance Proposals on Polkadot

### ISSUE THREAD

**Issue by danielbui12** [openguild-labs/open-contribution-bounty#24]
### Description
Step-by-step guide on how to create, propose, and implement governance proposals on the Polkadot network, including explain how it work

### Resources
- Bounty: $40
- Reference: https://polkadot.network/blog/a-walkthrough-of-polkadots-governance

**Comment by chainparser** [comment]
https://dev.to/polymawutor/how-to-implement-governance-proposals-on-polkadot-10hb
