### ISSUE TITLE
[Track 3 | Technical Blog] Integrating Smart Contracts in Polkadot

### ISSUE THREAD

**Issue by danielbui12** [openguild-labs/open-contribution-bounty#29]
### Description
Step-by-step instructions on how to use, integrate and deploy smart contracts on Polkadot using Ink!

### Resources
- Bounty: $40
- Reference: https://use.ink/

**Comment by HongThaiPham** [comment]
I write a blog [here](https://hongthaipham.github.io/blog/2024/07/25/ink-your-way-to-decentralized-apps-a-polkadot-smart-contract-tutorial) to submit for proof-of-work, can you review it please? @danielbui12 

let me know if any need to be modified

**Comment by danielbui12** [comment]
@HongThaiPham, great work! Have you applied for this track by filling out the form at this link https://noteforms.com/forms/open-contribution-bounty-ofolad?

Participants need to apply before starting work to ensure that multiple people don’t work on the same topic and to make it easier to support you in completing the bounty

**Comment by danielbui12** [comment]
@HongThaiPham great work sir, please submit it in the proof-of-work channel, we'll review it

**Comment by balqaasem** [comment]
Hi @chungquantin , How do I get started with this, the documentation and the discord channel are all kind of confusing on how to just do the work and submit it. Please help me explain it so I can quickly get started.
