### ISSUE TITLE
[Track 4 | Workshop Technical Activity] Open Hack ink! Starter

### ISSUE THREAD

**Issue by chungquantin** [openguild-labs/open-contribution-bounty#37]
### Description
Getting started with ink! smart contract development
Link to repo: https://github.com/openguild-labs/open-hack-ink-starter

### Resources
- Bounty: $80
- Reference: https://hongthaipham.github.io/blog/2024/07/25/ink-your-way-to-decentralized-apps-a-polkadot-smart-contract-tutorial

**Comment by balqaasem** [comment]
Hi @chungquantin , How do I get started with this, the documentation and the discord channel are all kind of confusing on how to just do the work and submit it. Please help me explain it so I can quickly get started.

**Comment by chungquantin** [comment]
This is done already.
