### ISSUE TITLE
[Track 4 | Workshop Technical Activity] Open Hack ISMP Starter

### ISSUE THREAD

**Issue by chungquantin** [openguild-labs/open-contribution-bounty#39]
### Description
Learn how to integrate ISMP to parachain for trust-free cross-chain communication
Link to repo: https://github.com/openguild-labs/open-hack-ismp-starter

### Resources
- Bounty: $80
- Reference: https://docs.hyperbridge.network/protocol/ismp

**Comment by shricastic** [comment]
whats the issue and whats the bounty for?

**Comment by chungquantin** [comment]
@shricastic Write a tutorial to integrate ISMP protocol to the Substrate runtime so it can use the functionalities of ISMP: https://docs.hyperbridge.network/protocol/ismp

Bounty for it is described here: https://openguild.wtf/bounty/activity-project-track

**Comment by chungquantin** [comment]
Dones.
